// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;

namespace Pulumi.Phpipam
{
    public static class Config
    {
        private static readonly Pulumi.Config __config = new Pulumi.Config("phpipam");
        /// <summary>
        /// The application ID required for API requests
        /// </summary>
        public static string? AppId { get; set; } = __config.Get("appId");

        /// <summary>
        /// The full URL (plus path) to the API endpoint
        /// </summary>
        public static string? Endpoint { get; set; } = __config.Get("endpoint");

        /// <summary>
        /// Whether server should be accessed without verifying the TLS certificate.
        /// </summary>
        public static bool? Insecure { get; set; } = __config.GetBoolean("insecure");

        /// <summary>
        /// The password of the PHPIPAM account
        /// </summary>
        public static string? Password { get; set; } = __config.Get("password");

        /// <summary>
        /// The username of the PHPIPAM account
        /// </summary>
        public static string? Username { get; set; } = __config.Get("username");

    }
}
