# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union
from . import _utilities, _tables

__all__ = [
    'GetFirstFreeAddressResult',
    'AwaitableGetFirstFreeAddressResult',
    'get_first_free_address',
]

@pulumi.output_type
class GetFirstFreeAddressResult:
    """
    A collection of values returned by getFirstFreeAddress.
    """
    def __init__(__self__, id=None, ip_address=None, subnet_id=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if ip_address and not isinstance(ip_address, str):
            raise TypeError("Expected argument 'ip_address' to be a str")
        pulumi.set(__self__, "ip_address", ip_address)
        if subnet_id and not isinstance(subnet_id, int):
            raise TypeError("Expected argument 'subnet_id' to be a int")
        pulumi.set(__self__, "subnet_id", subnet_id)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="ipAddress")
    def ip_address(self) -> str:
        return pulumi.get(self, "ip_address")

    @property
    @pulumi.getter(name="subnetId")
    def subnet_id(self) -> int:
        return pulumi.get(self, "subnet_id")


class AwaitableGetFirstFreeAddressResult(GetFirstFreeAddressResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetFirstFreeAddressResult(
            id=self.id,
            ip_address=self.ip_address,
            subnet_id=self.subnet_id)


def get_first_free_address(subnet_id: Optional[int] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetFirstFreeAddressResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['subnetId'] = subnet_id
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = _utilities.get_version()
    __ret__ = pulumi.runtime.invoke('phpipam:index/getFirstFreeAddress:getFirstFreeAddress', __args__, opts=opts, typ=GetFirstFreeAddressResult).value

    return AwaitableGetFirstFreeAddressResult(
        id=__ret__.id,
        ip_address=__ret__.ip_address,
        subnet_id=__ret__.subnet_id)
