// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi/config"
)

// The application ID required for API requests
func GetAppId(ctx *pulumi.Context) string {
	return config.Get(ctx, "phpipam:appId")
}

// The full URL (plus path) to the API endpoint
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "phpipam:endpoint")
}

// Whether server should be accessed without verifying the TLS certificate.
func GetInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "phpipam:insecure")
}

// The password of the PHPIPAM account
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "phpipam:password")
}

// The username of the PHPIPAM account
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "phpipam:username")
}
