// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("phpipam");

/**
 * The application ID required for API requests
 */
export let appId: string | undefined = __config.get("appId");
/**
 * The full URL (plus path) to the API endpoint
 */
export let endpoint: string | undefined = __config.get("endpoint");
/**
 * Whether server should be accessed without verifying the TLS certificate.
 */
export let insecure: boolean | undefined = __config.getObject<boolean>("insecure");
/**
 * The password of the PHPIPAM account
 */
export let password: string | undefined = __config.get("password");
/**
 * The username of the PHPIPAM account
 */
export let username: string | undefined = __config.get("username");
