// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package phpipam

import (
	"reflect"

	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

// The provider type for the phpipam package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:phpipam", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// The application ID required for API requests
	AppId *string `pulumi:"appId"`
	// The full URL (plus path) to the API endpoint
	Endpoint *string `pulumi:"endpoint"`
	// Whether server should be accessed without verifying the TLS certificate.
	Insecure *bool `pulumi:"insecure"`
	// The password of the PHPIPAM account
	Password *string `pulumi:"password"`
	// The username of the PHPIPAM account
	Username *string `pulumi:"username"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// The application ID required for API requests
	AppId pulumi.StringPtrInput
	// The full URL (plus path) to the API endpoint
	Endpoint pulumi.StringPtrInput
	// Whether server should be accessed without verifying the TLS certificate.
	Insecure pulumi.BoolPtrInput
	// The password of the PHPIPAM account
	Password pulumi.StringPtrInput
	// The username of the PHPIPAM account
	Username pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}
