// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAddress(args?: GetAddressArgs, opts?: pulumi.InvokeOptions): Promise<GetAddressResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("phpipam:index/getAddress:getAddress", {
        "addressId": args.addressId,
        "customFieldFilter": args.customFieldFilter,
        "description": args.description,
        "hostname": args.hostname,
        "ipAddress": args.ipAddress,
        "subnetId": args.subnetId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAddress.
 */
export interface GetAddressArgs {
    readonly addressId?: number;
    readonly customFieldFilter?: {[key: string]: any};
    readonly description?: string;
    readonly hostname?: string;
    readonly ipAddress?: string;
    readonly subnetId?: number;
}

/**
 * A collection of values returned by getAddress.
 */
export interface GetAddressResult {
    readonly addressId: number;
    readonly customFieldFilter?: {[key: string]: any};
    readonly customFields: {[key: string]: any};
    readonly description: string;
    readonly deviceId: number;
    readonly editDate: string;
    readonly excludePing: boolean;
    readonly hostname: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ipAddress: string;
    readonly isGateway: boolean;
    readonly lastSeen: string;
    readonly macAddress: string;
    readonly note: string;
    readonly owner: string;
    readonly ptrRecordId: number;
    readonly skipPtrRecord: boolean;
    readonly stateTagId: number;
    readonly subnetId: number;
    readonly switchPortLabel: string;
}
