// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getFirstFreeSubnet(args: GetFirstFreeSubnetArgs, opts?: pulumi.InvokeOptions): Promise<GetFirstFreeSubnetResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("phpipam:index/getFirstFreeSubnet:getFirstFreeSubnet", {
        "subnetId": args.subnetId,
        "subnetMask": args.subnetMask,
    }, opts);
}

/**
 * A collection of arguments for invoking getFirstFreeSubnet.
 */
export interface GetFirstFreeSubnetArgs {
    readonly subnetId: number;
    readonly subnetMask: number;
}

/**
 * A collection of values returned by getFirstFreeSubnet.
 */
export interface GetFirstFreeSubnetResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ipAddress: string;
    readonly subnetId: number;
    readonly subnetMask: number;
}
