// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getFirstFreeAddress(args: GetFirstFreeAddressArgs, opts?: pulumi.InvokeOptions): Promise<GetFirstFreeAddressResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("phpipam:index/getFirstFreeAddress:getFirstFreeAddress", {
        "subnetId": args.subnetId,
    }, opts);
}

/**
 * A collection of arguments for invoking getFirstFreeAddress.
 */
export interface GetFirstFreeAddressArgs {
    readonly subnetId: number;
}

/**
 * A collection of values returned by getFirstFreeAddress.
 */
export interface GetFirstFreeAddressResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ipAddress: string;
    readonly subnetId: number;
}
