// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSubnet(args?: GetSubnetArgs, opts?: pulumi.InvokeOptions): Promise<GetSubnetResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("phpipam:index/getSubnet:getSubnet", {
        "customFieldFilter": args.customFieldFilter,
        "description": args.description,
        "descriptionMatch": args.descriptionMatch,
        "sectionId": args.sectionId,
        "subnetAddress": args.subnetAddress,
        "subnetId": args.subnetId,
        "subnetMask": args.subnetMask,
    }, opts);
}

/**
 * A collection of arguments for invoking getSubnet.
 */
export interface GetSubnetArgs {
    readonly customFieldFilter?: {[key: string]: any};
    readonly description?: string;
    readonly descriptionMatch?: string;
    readonly sectionId?: number;
    readonly subnetAddress?: string;
    readonly subnetId?: number;
    readonly subnetMask?: number;
}

/**
 * A collection of values returned by getSubnet.
 */
export interface GetSubnetResult {
    readonly allowIpRequests: boolean;
    readonly createPtrRecords: boolean;
    readonly customFieldFilter?: {[key: string]: any};
    readonly customFields: {[key: string]: any};
    readonly description: string;
    readonly descriptionMatch?: string;
    readonly displayHostnames: boolean;
    readonly editDate: string;
    readonly gateway: {[key: string]: any};
    readonly gatewayId: string;
    readonly hostDiscoveryEnabled: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly includeInPing: boolean;
    readonly isFolder: boolean;
    readonly isFull: boolean;
    readonly linkedSubnetId: number;
    readonly locationId: number;
    readonly masterSubnetId: number;
    readonly nameserverId: number;
    readonly parentSubnetId: number;
    readonly permissions: string;
    readonly scanAgentId: number;
    readonly sectionId: number;
    readonly showName: boolean;
    readonly subnetAddress: string;
    readonly subnetId: number;
    readonly subnetMask: number;
    readonly utilizationThreshold: number;
    readonly vlanId: number;
    readonly vrfId: number;
}
