// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getVlan(args?: GetVlanArgs, opts?: pulumi.InvokeOptions): Promise<GetVlanResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("phpipam:index/getVlan:getVlan", {
        "number": args.number,
        "vlanId": args.vlanId,
    }, opts);
}

/**
 * A collection of arguments for invoking getVlan.
 */
export interface GetVlanArgs {
    readonly number?: number;
    readonly vlanId?: number;
}

/**
 * A collection of values returned by getVlan.
 */
export interface GetVlanResult {
    readonly customFields: {[key: string]: any};
    readonly description: string;
    readonly editDate: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly l2DomainId: number;
    readonly name: string;
    readonly number: number;
    readonly vlanId: number;
}
