// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Export members:
export * from "./address";
export * from "./firstFreeAddress";
export * from "./firstFreeSubnet";
export * from "./getAddress";
export * from "./getAddresses";
export * from "./getFirstFreeAddress";
export * from "./getFirstFreeSubnet";
export * from "./getSection";
export * from "./getSubnet";
export * from "./getSubnets";
export * from "./getVlan";
export * from "./provider";
export * from "./section";
export * from "./subnet";
export * from "./vlan";

// Export sub-modules:
import * as config from "./config";
export {config};
