// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Section extends pulumi.CustomResource {
    /**
     * Get an existing Section resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SectionState, opts?: pulumi.CustomResourceOptions): Section {
        return new Section(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'phpipam:index/section:Section';

    /**
     * Returns true if the given object is an instance of Section.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Section {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Section.__pulumiType;
    }

    public readonly description!: pulumi.Output<string>;
    public readonly displayOrder!: pulumi.Output<number>;
    public readonly dnsResolverId!: pulumi.Output<number>;
    public /*out*/ readonly editDate!: pulumi.Output<string>;
    public readonly masterSectionId!: pulumi.Output<number>;
    public readonly name!: pulumi.Output<string>;
    public /*out*/ readonly permissions!: pulumi.Output<string>;
    public /*out*/ readonly sectionId!: pulumi.Output<number>;
    public readonly showSupernetOnly!: pulumi.Output<boolean>;
    public readonly showVlanInSubnetListing!: pulumi.Output<boolean>;
    public readonly showVrfInSubnetListing!: pulumi.Output<boolean>;
    public readonly strictMode!: pulumi.Output<boolean>;
    public readonly subnetOrdering!: pulumi.Output<string>;

    /**
     * Create a Section resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SectionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SectionArgs | SectionState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as SectionState | undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["displayOrder"] = state ? state.displayOrder : undefined;
            inputs["dnsResolverId"] = state ? state.dnsResolverId : undefined;
            inputs["editDate"] = state ? state.editDate : undefined;
            inputs["masterSectionId"] = state ? state.masterSectionId : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["permissions"] = state ? state.permissions : undefined;
            inputs["sectionId"] = state ? state.sectionId : undefined;
            inputs["showSupernetOnly"] = state ? state.showSupernetOnly : undefined;
            inputs["showVlanInSubnetListing"] = state ? state.showVlanInSubnetListing : undefined;
            inputs["showVrfInSubnetListing"] = state ? state.showVrfInSubnetListing : undefined;
            inputs["strictMode"] = state ? state.strictMode : undefined;
            inputs["subnetOrdering"] = state ? state.subnetOrdering : undefined;
        } else {
            const args = argsOrState as SectionArgs | undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["displayOrder"] = args ? args.displayOrder : undefined;
            inputs["dnsResolverId"] = args ? args.dnsResolverId : undefined;
            inputs["masterSectionId"] = args ? args.masterSectionId : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["showSupernetOnly"] = args ? args.showSupernetOnly : undefined;
            inputs["showVlanInSubnetListing"] = args ? args.showVlanInSubnetListing : undefined;
            inputs["showVrfInSubnetListing"] = args ? args.showVrfInSubnetListing : undefined;
            inputs["strictMode"] = args ? args.strictMode : undefined;
            inputs["subnetOrdering"] = args ? args.subnetOrdering : undefined;
            inputs["editDate"] = undefined /*out*/;
            inputs["permissions"] = undefined /*out*/;
            inputs["sectionId"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(Section.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Section resources.
 */
export interface SectionState {
    readonly description?: pulumi.Input<string>;
    readonly displayOrder?: pulumi.Input<number>;
    readonly dnsResolverId?: pulumi.Input<number>;
    readonly editDate?: pulumi.Input<string>;
    readonly masterSectionId?: pulumi.Input<number>;
    readonly name?: pulumi.Input<string>;
    readonly permissions?: pulumi.Input<string>;
    readonly sectionId?: pulumi.Input<number>;
    readonly showSupernetOnly?: pulumi.Input<boolean>;
    readonly showVlanInSubnetListing?: pulumi.Input<boolean>;
    readonly showVrfInSubnetListing?: pulumi.Input<boolean>;
    readonly strictMode?: pulumi.Input<boolean>;
    readonly subnetOrdering?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Section resource.
 */
export interface SectionArgs {
    readonly description?: pulumi.Input<string>;
    readonly displayOrder?: pulumi.Input<number>;
    readonly dnsResolverId?: pulumi.Input<number>;
    readonly masterSectionId?: pulumi.Input<number>;
    readonly name?: pulumi.Input<string>;
    readonly showSupernetOnly?: pulumi.Input<boolean>;
    readonly showVlanInSubnetListing?: pulumi.Input<boolean>;
    readonly showVrfInSubnetListing?: pulumi.Input<boolean>;
    readonly strictMode?: pulumi.Input<boolean>;
    readonly subnetOrdering?: pulumi.Input<string>;
}
