// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Subnet extends pulumi.CustomResource {
    /**
     * Get an existing Subnet resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SubnetState, opts?: pulumi.CustomResourceOptions): Subnet {
        return new Subnet(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'phpipam:index/subnet:Subnet';

    /**
     * Returns true if the given object is an instance of Subnet.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Subnet {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Subnet.__pulumiType;
    }

    public readonly allowIpRequests!: pulumi.Output<boolean>;
    public readonly createPtrRecords!: pulumi.Output<boolean>;
    public readonly customFields!: pulumi.Output<{[key: string]: any} | undefined>;
    public readonly description!: pulumi.Output<string>;
    public readonly displayHostnames!: pulumi.Output<boolean>;
    public /*out*/ readonly editDate!: pulumi.Output<string>;
    public /*out*/ readonly gateway!: pulumi.Output<{[key: string]: any}>;
    public /*out*/ readonly gatewayId!: pulumi.Output<string>;
    public /*out*/ readonly hostDiscoveryEnabled!: pulumi.Output<boolean>;
    public readonly includeInPing!: pulumi.Output<boolean>;
    public /*out*/ readonly isFolder!: pulumi.Output<boolean>;
    public readonly isFull!: pulumi.Output<boolean>;
    public readonly linkedSubnetId!: pulumi.Output<number>;
    public /*out*/ readonly locationId!: pulumi.Output<number>;
    public readonly masterSubnetId!: pulumi.Output<number>;
    public readonly nameserverId!: pulumi.Output<number>;
    public /*out*/ readonly parentSubnetId!: pulumi.Output<number>;
    public /*out*/ readonly permissions!: pulumi.Output<string>;
    public readonly scanAgentId!: pulumi.Output<number>;
    public readonly sectionId!: pulumi.Output<number>;
    public readonly showName!: pulumi.Output<boolean>;
    public readonly subnetAddress!: pulumi.Output<string>;
    public /*out*/ readonly subnetId!: pulumi.Output<number>;
    public readonly subnetMask!: pulumi.Output<number>;
    public readonly utilizationThreshold!: pulumi.Output<number>;
    public readonly vlanId!: pulumi.Output<number>;
    public readonly vrfId!: pulumi.Output<number>;

    /**
     * Create a Subnet resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SubnetArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SubnetArgs | SubnetState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as SubnetState | undefined;
            inputs["allowIpRequests"] = state ? state.allowIpRequests : undefined;
            inputs["createPtrRecords"] = state ? state.createPtrRecords : undefined;
            inputs["customFields"] = state ? state.customFields : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["displayHostnames"] = state ? state.displayHostnames : undefined;
            inputs["editDate"] = state ? state.editDate : undefined;
            inputs["gateway"] = state ? state.gateway : undefined;
            inputs["gatewayId"] = state ? state.gatewayId : undefined;
            inputs["hostDiscoveryEnabled"] = state ? state.hostDiscoveryEnabled : undefined;
            inputs["includeInPing"] = state ? state.includeInPing : undefined;
            inputs["isFolder"] = state ? state.isFolder : undefined;
            inputs["isFull"] = state ? state.isFull : undefined;
            inputs["linkedSubnetId"] = state ? state.linkedSubnetId : undefined;
            inputs["locationId"] = state ? state.locationId : undefined;
            inputs["masterSubnetId"] = state ? state.masterSubnetId : undefined;
            inputs["nameserverId"] = state ? state.nameserverId : undefined;
            inputs["parentSubnetId"] = state ? state.parentSubnetId : undefined;
            inputs["permissions"] = state ? state.permissions : undefined;
            inputs["scanAgentId"] = state ? state.scanAgentId : undefined;
            inputs["sectionId"] = state ? state.sectionId : undefined;
            inputs["showName"] = state ? state.showName : undefined;
            inputs["subnetAddress"] = state ? state.subnetAddress : undefined;
            inputs["subnetId"] = state ? state.subnetId : undefined;
            inputs["subnetMask"] = state ? state.subnetMask : undefined;
            inputs["utilizationThreshold"] = state ? state.utilizationThreshold : undefined;
            inputs["vlanId"] = state ? state.vlanId : undefined;
            inputs["vrfId"] = state ? state.vrfId : undefined;
        } else {
            const args = argsOrState as SubnetArgs | undefined;
            if (!args || args.sectionId === undefined) {
                throw new Error("Missing required property 'sectionId'");
            }
            if (!args || args.subnetAddress === undefined) {
                throw new Error("Missing required property 'subnetAddress'");
            }
            if (!args || args.subnetMask === undefined) {
                throw new Error("Missing required property 'subnetMask'");
            }
            inputs["allowIpRequests"] = args ? args.allowIpRequests : undefined;
            inputs["createPtrRecords"] = args ? args.createPtrRecords : undefined;
            inputs["customFields"] = args ? args.customFields : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["displayHostnames"] = args ? args.displayHostnames : undefined;
            inputs["includeInPing"] = args ? args.includeInPing : undefined;
            inputs["isFull"] = args ? args.isFull : undefined;
            inputs["linkedSubnetId"] = args ? args.linkedSubnetId : undefined;
            inputs["masterSubnetId"] = args ? args.masterSubnetId : undefined;
            inputs["nameserverId"] = args ? args.nameserverId : undefined;
            inputs["scanAgentId"] = args ? args.scanAgentId : undefined;
            inputs["sectionId"] = args ? args.sectionId : undefined;
            inputs["showName"] = args ? args.showName : undefined;
            inputs["subnetAddress"] = args ? args.subnetAddress : undefined;
            inputs["subnetMask"] = args ? args.subnetMask : undefined;
            inputs["utilizationThreshold"] = args ? args.utilizationThreshold : undefined;
            inputs["vlanId"] = args ? args.vlanId : undefined;
            inputs["vrfId"] = args ? args.vrfId : undefined;
            inputs["editDate"] = undefined /*out*/;
            inputs["gateway"] = undefined /*out*/;
            inputs["gatewayId"] = undefined /*out*/;
            inputs["hostDiscoveryEnabled"] = undefined /*out*/;
            inputs["isFolder"] = undefined /*out*/;
            inputs["locationId"] = undefined /*out*/;
            inputs["parentSubnetId"] = undefined /*out*/;
            inputs["permissions"] = undefined /*out*/;
            inputs["subnetId"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(Subnet.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Subnet resources.
 */
export interface SubnetState {
    readonly allowIpRequests?: pulumi.Input<boolean>;
    readonly createPtrRecords?: pulumi.Input<boolean>;
    readonly customFields?: pulumi.Input<{[key: string]: any}>;
    readonly description?: pulumi.Input<string>;
    readonly displayHostnames?: pulumi.Input<boolean>;
    readonly editDate?: pulumi.Input<string>;
    readonly gateway?: pulumi.Input<{[key: string]: any}>;
    readonly gatewayId?: pulumi.Input<string>;
    readonly hostDiscoveryEnabled?: pulumi.Input<boolean>;
    readonly includeInPing?: pulumi.Input<boolean>;
    readonly isFolder?: pulumi.Input<boolean>;
    readonly isFull?: pulumi.Input<boolean>;
    readonly linkedSubnetId?: pulumi.Input<number>;
    readonly locationId?: pulumi.Input<number>;
    readonly masterSubnetId?: pulumi.Input<number>;
    readonly nameserverId?: pulumi.Input<number>;
    readonly parentSubnetId?: pulumi.Input<number>;
    readonly permissions?: pulumi.Input<string>;
    readonly scanAgentId?: pulumi.Input<number>;
    readonly sectionId?: pulumi.Input<number>;
    readonly showName?: pulumi.Input<boolean>;
    readonly subnetAddress?: pulumi.Input<string>;
    readonly subnetId?: pulumi.Input<number>;
    readonly subnetMask?: pulumi.Input<number>;
    readonly utilizationThreshold?: pulumi.Input<number>;
    readonly vlanId?: pulumi.Input<number>;
    readonly vrfId?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Subnet resource.
 */
export interface SubnetArgs {
    readonly allowIpRequests?: pulumi.Input<boolean>;
    readonly createPtrRecords?: pulumi.Input<boolean>;
    readonly customFields?: pulumi.Input<{[key: string]: any}>;
    readonly description?: pulumi.Input<string>;
    readonly displayHostnames?: pulumi.Input<boolean>;
    readonly includeInPing?: pulumi.Input<boolean>;
    readonly isFull?: pulumi.Input<boolean>;
    readonly linkedSubnetId?: pulumi.Input<number>;
    readonly masterSubnetId?: pulumi.Input<number>;
    readonly nameserverId?: pulumi.Input<number>;
    readonly scanAgentId?: pulumi.Input<number>;
    readonly sectionId: pulumi.Input<number>;
    readonly showName?: pulumi.Input<boolean>;
    readonly subnetAddress: pulumi.Input<string>;
    readonly subnetMask: pulumi.Input<number>;
    readonly utilizationThreshold?: pulumi.Input<number>;
    readonly vlanId?: pulumi.Input<number>;
    readonly vrfId?: pulumi.Input<number>;
}
